# Generated by Django 5.1.3 on 2024-12-06 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accountsUsersApp', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='preferred_address',
        ),
    ]
