# Generated by Django 5.1.3 on 2024-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsUsersApp', '0004_remove_customuser_preferred_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line_1', models.CharField(help_text='Address Line 1', max_length=100)),
                ('address_line_2', models.CharField(blank=True, help_text='Address Line 2', max_length=100, null=True)),
                ('city', models.CharField(help_text='City', max_length=20)),
                ('country', models.CharField(help_text='Country', max_length=20)),
                ('zipcode', models.CharField(help_text='Zip Code', max_length=10)),
            ],
        ),
    ]
