# Generated by Django 5.1.3 on 2024-12-06 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsUsersApp', '0005_shippingaddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='shipping_address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='accountsUsersApp.shippingaddress'),
        ),
    ]
