# Generated by Django 5.1.3 on 2024-12-08 17:10

import accountsUsersApp.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsUsersApp', '0006_customuser_shipping_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Funds',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sum', models.DecimalField(decimal_places=2, default=0.0, help_text='Deposit here', max_digits=4, validators=[accountsUsersApp.validators.AllNumbersValidator()])),
                ('last_deposit', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
                ('last_buy', models.DecimalField(decimal_places=2, default=0.0, max_digits=4)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='funds',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funds', to='accountsUsersApp.funds'),
        ),
    ]
