# Generated by Django 5.1.3 on 2024-12-08 19:29

import accountsUsersApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsUsersApp', '0008_funds_temporary_cvv_funds_temporary_card_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='temporary_CVV',
            field=models.CharField(default='', max_length=3, validators=[accountsUsersApp.validators.AllNumbersValidator()]),
        ),
    ]
