# Generated by Django 5.1.3 on 2024-12-09 11:48

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsUsersApp', '0013_alter_funds_last_deposit_alter_funds_sum_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(default='', max_length=30)),
                ('item_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=6)),
                ('item_image_url', models.CharField(default='')),
            ],
        ),
        migrations.AlterField(
            model_name='funds',
            name='temporary_expiration_date',
            field=models.DateField(default=datetime.date(2024, 12, 9)),
        ),
        migrations.AddField(
            model_name='customuser',
            name='cart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='accountsUsersApp.cart'),
        ),
    ]
