# Generated by Django 5.1.3 on 2024-12-09 15:47

import accountsUsersApp.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accountsUsersApp', '0017_alter_cart_item_ids'),
    ]

    operations = [
        migrations.AlterField(
            model_name='funds',
            name='temporary_card_number',
            field=models.CharField(default='', max_length=16, validators=[accountsUsersApp.validators.TenCharactersValidator(), accountsUsersApp.validators.AllNumbersValidator()]),
        ),
        migrations.AlterField(
            model_name='funds',
            name='temporary_placeholder_name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
