# Generated by Django 5.1.3 on 2024-12-07 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(error_messages={'Name should be unique': 'A product with this name already exists.'}, help_text='Name', max_length=20, unique=True)),
                ('price', models.FloatField(help_text='Price')),
                ('available', models.BooleanField(default=True, help_text='Is this product available?')),
                ('image_url', models.URLField(help_text='Image URL')),
            ],
        ),
    ]
